-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th6 17, 2021 lúc 07:43 PM
-- Phiên bản máy phục vụ: 10.4.19-MariaDB
-- Phiên bản PHP: 8.0.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `book`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `book`
--

CREATE TABLE `book` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(550) COLLATE utf8_unicode_ci DEFAULT NULL,
  `img` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` tinyint(1) NOT NULL,
  `class` int(2) NOT NULL,
  `author` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `publishing` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `year` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `link` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `idcate` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `book`
--

INSERT INTO `book` (`id`, `name`, `slug`, `img`, `type`, `class`, `author`, `publishing`, `year`, `description`, `link`, `idcate`) VALUES
(18, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(19, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 2, 2, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(20, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 3),
(21, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 2, 2, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(22, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 2),
(23, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 2, 2, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(25, 'engbook Long Dep tr', 'engbook-long-dep-tr-25', '2.jpeg', 1, 0, 'Tác gi', 'Nhà xuất bả', '200', '<p>Long dep trai&nbsp;</p>\r\n', 'lin', 1),
(26, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(27, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(28, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(29, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(30, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(31, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(32, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(33, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(34, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(35, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(36, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(37, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1),
(38, 'Smiles 1 Special Edition', NULL, 'S6-AB.png', 1, 1, 'JENNY DOOLEY', ' Nhà xuất bản Giáo Dục Việt Nam', '2020', 'Tiếng Anh 7, Tập Một được Nhà xuất bản Giáo dục Việt Nam tổ chức biên soạn theo Chương trình Giáo dục phổ thông môn Tiếng Anh thí điểm cấp Trung học cơ sở do Bộ Giáo dục và Đào tạo ban hành theo Quyết định số 01/QĐ-BGDĐT ngày 03 tháng 01 năm 2012, tiếp theo Tiếng Anh 6. Sách được biên soạn theo đường hướng giao tiếp, giúp học sinh sử dụng ngữ liệu (ngữ âm, từ vựng, ngữ pháp) để phát triển năng lực giao tiếp bằng tiếng Anh thông qua bốn kĩ năng nghe, nói, đọc và viết, trong đó, ưu tiên phát triển hai kĩ năng nghe và nói. Trong Tiếng Anh 7, Tập Một, việc học là trung tâm, học sinh là chủ thể của quá trình dạy học, trong đó tâm lí lứa tuổi của học sinh Trung học cơ sở, các đặc điểm văn hoá của Việt Nam và của các nước trên thế giới, đặc biệt là của các nước nói tiếng Anh, được coi trọng. Tiếng Anh 7, Tập một được biên soạn xoay quanh hai chủ điểm (Theme) gần gũi với học sinh: Our Communities và Our Heritage. Mỗi chủ điểm được chia thành ba đơn vị bài học (Unit) tương ứng với ba chủ đề (Topic) của chương trình. Sau mỗi chủ điểm là một bài ôn (Review) tập trung vào kiến thức ngôn ngữ và kĩ năng ngôn ngữ học sinh đã được học và rèn luyện. Tiếng Anh 7, Tập một được biên soạn trên cơ sở những kinh nghiệm thực tiễn của việc dạy tiếng Anh Trung học cơ sở ở Việt Nam với sự hợp tác chặt chẽ về chuyên môn và kĩ thuật của Tập đoàn Xuất bản Giáo dục Pearson.\r\n\r\n', 'http://localhost/engbook/course-detail.html', 1);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `book`
--
ALTER TABLE `book`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_book_cate` (`idcate`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `book`
--
ALTER TABLE `book`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `book`
--
ALTER TABLE `book`
  ADD CONSTRAINT `fk_book_cate` FOREIGN KEY (`idcate`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
